#端口
server:
  port: 8888
  servlet:
    context-path: /retwisApi

#mysql redis
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/retwisapi?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&serverTimezone=Asia/Shanghai

  redis:
    port: 6379
    host: localhost
    #使用qq邮箱发送邮件
  mail:
    username: 1401501786@qq.com
    password: qfpwqtbjzadbhfej
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
  #rabbitMQ
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    virtual-host: /


#mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

#七牛云存储
qiniu:
  accessKey:
  secretKey:
  bucket:
  prefix:

